language: node_js
node_js:
- node
- lts/*


stages:
  - test
  - name: deploy

jobs:
  include:
    - stage: deploy
      node_js: node
      script: npm run export-gh-pages
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep-history: true
        local-dir: out/
        on:
          branch: master
