language: node_js
node_js:
- 10

after_success: npm run export-gh-pages
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: out/
  on:
    branch: master
